### ISSUE TITLE
Results unreliable

### ISSUE THREAD

**Issue by Epi-NMT** [HAHA-DL/MLDG#2]
Thanks for your implementation.

I have run run_mldg.sh two times and check the result in file run_1 and run_2.

In each of the logs_mldg_(0-3), I check the heldout_test_log.txt and flag_log.txt.

I got following results:
run_1:
logs_mldg_0:  unseen_index=0   heldout_test_log=0.70849
logs_mldg_1:  unseen_index=1   heldout_test_log=0.47440
logs_mldg_2:  unseen_index=2   heldout_test_log=0.95449
logs_mldg_3:  unseen_index=3   heldout_test_log=0.39246
run_2:
logs_mldg_0:  unseen_index=0   heldout_test_log=0.72363
logs_mldg_1:  unseen_index=1   heldout_test_log=0.48677
logs_mldg_2:  unseen_index=2   heldout_test_log=0.95748
logs_mldg_3:  unseen_index=3   heldout_test_log=0.40697
The average is just around 0.63, and each result is much different from the result reported in paper. So it is hard to believe this is the accuracy regarding each unseen domain(A C P S).

I don't change any parameters in run_mldg.sh and main_mldg.py 
Did I do something wrong or I misunderstood something?

Thank you very much.

**Comment by HAHA-DL** [comment]
@keyu07 Hi, thanks for your interest in our paper and code. This is an MLP version demo code which is different from the end-2-end training in the published paper.

**Comment by Epi-NMT** [comment]
Can you provide original version that can reproduce the result?

**Comment by HAHA-DL** [comment]
@keyu07 I provide both conv2d and linear functions in ops.py. You can extend it to the AlexNet version and achieve similar performance.

**Comment by Yash-Vardhan-Sharma** [comment]
hey
I too got following results:
run_1:
logs_mldg_0: unseen_index=0 heldout_test_log=0.70849
0.70849 is more than the paper result by 5%(in FC) , how is it possible ?

**Comment by dali-dl** [comment]
@Yash-Vardhan-Sharma 
Thanks for your interests in our paper.

This was originally for demo purpose and for people to easily run the algorithm, so the backbone is just a shallow MLP trained with the pre-extracted ResNet-18 feature. That is why the result is different from the reported.

Ok, I will update the repo to replace the backbone as the one used in the paper to remove confusion.

**Comment by Yash-Vardhan-Sharma** [comment]
Its really interesting to see that your code is giving more accuracy for heldout domain even wrt current sota .
What is the paper's orignal backbone ?
